# THIS WILL BE PUBLIC. DON'T ENTER ANY VARIABLES YOU DON'T WANT THE WORLD TO SEE.
# YOU CAN OVERRIDE ANY VARIABLES BY SETTING DUMMY VALUES AND OVERRIDING THEM IN FROM THE COMMAND LINE.

envName = "prod"